extend type Query {
  """
  ✨ Look up a single `AuditLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  auditLog(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AuditLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AuditLog_FirstRow
  ): AuditLog @fdc_generated(from: "AuditLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Conversation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  conversation(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Conversation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Conversation_FirstRow
  ): Conversation @fdc_generated(from: "Conversation", purpose: QUERY_SINGLE)
  """
  ✨ List `AuditLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  auditLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: AuditLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AuditLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AuditLog_Having
  ): [AuditLog!]! @fdc_generated(from: "AuditLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Conversation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  conversations(
    """
    Filter condition to narrow down the query results.
    """
    where: Conversation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Conversation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Conversation_Having
  ): [Conversation!]! @fdc_generated(from: "Conversation", purpose: QUERY_MULTIPLE)
}
